# Generated by Django 2.0.6 on 2019-09-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=80)),
                ('qtdPrevistoMes', models.FloatField()),
                ('preco', models.FloatField()),
                ('precoMaximo', models.FloatField()),
            ],
        ),
    ]
